export * from './header/Header'
export * from './movies/Movies'
export * from './movieCard/MovieCard'
export * from './footer/Footer'
export * from './headerMenu/HeaderMenu'
export * from './genre/Genre'
export * from './movie/Movie'